name: youtube_music_copy
description: youtube music  copy

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  simple_animations: ^5.0.1
  transparent_image: ^2.0.1
  sensors_plus: ^3.0.2
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_lint:
    path: ../../dart_lint

flutter:
  uses-material-design: true
